### ISSUE TITLE
Trouble importing 

### ISSUE THREAD

**Issue by ratnadeep1982** [buettnerlab/pytometry_legacy#12]
Hi, I tried importing Pytometry and this is the error I receive:

Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytometry as pm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\pytometry\__init__.py", line 25, in <module>
    from . import plotting as pl
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\pytometry\plotting\__init__.py", line 1, in <module>
    from ._histogram import plotdata
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\pytometry\plotting\_histogram.py", line 5, in <module>
    from anndata import AnnData
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
    import h5py
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.

Any help would be much appreciated.

Thanks in advance!

**Comment by mbuttner** [comment]
Hi @ratnadeep1982 

thanks for reporting the issue. It looks like a problem with the `h5py` package. Please have a look at https://github.com/h5py/h5py/issues/2037

**Comment by ratnadeep1982** [comment]
Thanks! I solved the issue by:
$> conda remove --force h5py
$> pip install h5py
